.PHONY: clean All

All:
	@echo "----------Building project:[ wxFrame_GUI - Debug ]----------"
	@cd "wxFrame_GUI" && "$(MAKE)" -f  "wxFrame_GUI.mk"
clean:
	@echo "----------Cleaning project:[ wxFrame_GUI - Debug ]----------"
	@cd "wxFrame_GUI" && "$(MAKE)" -f  "wxFrame_GUI.mk" clean
