//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _WXFRAME_GUI_WXFRAME_GUI_WXCRAFTER_BASE_CLASSES_H
#define _WXFRAME_GUI_WXFRAME_GUI_WXCRAFTER_BASE_CLASSES_H

// clang-format off
#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/panel.h>
#include <wx/stattext.h>
#include <wx/button.h>
#include <wx/textctrl.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif

// clang-format on

class MainFrameBaseClass : public wxFrame
{
protected:
    wxPanel* m_mainPanel;
    wxStaticText* m_staticText21;
    wxStaticText* m_StaticText22;
    wxButton* m_btnOk;
    wxButton* m_btnNOk;
    wxTextCtrl* m_txtValor1;
    wxTextCtrl* m_txtValor2;
    wxStaticText* m_staticText31;
    wxTextCtrl* m_txtResultado;

protected:
    virtual void btnClickSoma(wxCommandEvent& event)
    {
        event.Skip();
    }
    virtual void btnClickSubtracao(wxCommandEvent& event)
    {
        event.Skip();
    }

public:
    wxStaticText* GetStaticText21()
    {
        return m_staticText21;
    }
    wxStaticText* GetStaticText22()
    {
        return m_StaticText22;
    }
    wxButton* GetBtnOk()
    {
        return m_btnOk;
    }
    wxButton* GetBtnNOk()
    {
        return m_btnNOk;
    }
    wxTextCtrl* GetTxtValor1()
    {
        return m_txtValor1;
    }
    wxTextCtrl* GetTxtValor2()
    {
        return m_txtValor2;
    }
    wxStaticText* GetStaticText31()
    {
        return m_staticText31;
    }
    wxTextCtrl* GetTxtResultado()
    {
        return m_txtResultado;
    }
    wxPanel* GetMainPanel()
    {
        return m_mainPanel;
    }
    MainFrameBaseClass(wxWindow* parent,
        wxWindowID id = wxID_ANY,
        const wxString& title = _("My Frame"),
        const wxPoint& pos = wxDefaultPosition,
        const wxSize& size = wxSize(500, 300),
        long style = wxCAPTION | wxRESIZE_BORDER | wxMAXIMIZE_BOX | wxMINIMIZE_BOX | wxSYSTEM_MENU | wxCLOSE_BOX);
    virtual ~MainFrameBaseClass();
};

#endif
