//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "wxcrafter.h"

// Declare the bitmap loading function
extern void wxC9ED9InitBitmapResources();

static bool bBitmapLoaded = false;

MainFrameBaseClass::MainFrameBaseClass(wxWindow* parent,
    wxWindowID id,
    const wxString& title,
    const wxPoint& pos,
    const wxSize& size,
    long style)
    : wxFrame(parent, id, title, pos, size, style)
{
    if(!bBitmapLoaded) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC9ED9InitBitmapResources();
        bBitmapLoaded = true;
    }

    wxBoxSizer* boxSizer1 = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(boxSizer1);

    m_mainPanel = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1, -1)), wxTAB_TRAVERSAL);

    boxSizer1->Add(m_mainPanel, 1, wxEXPAND, WXC_FROM_DIP(5));

    wxBoxSizer* boxSizer11 = new wxBoxSizer(wxHORIZONTAL);
    m_mainPanel->SetSizer(boxSizer11);

    wxBoxSizer* boxSizer13 = new wxBoxSizer(wxVERTICAL);

    boxSizer11->Add(boxSizer13, 1, wxALL | wxEXPAND, WXC_FROM_DIP(5));

    m_staticText21 = new wxStaticText(
        m_mainPanel, wxID_ANY, _("Valor 1"), wxDefaultPosition, wxDLG_UNIT(m_mainPanel, wxSize(-1, -1)), 0);

    boxSizer13->Add(m_staticText21, 0, wxALL | wxALIGN_CENTER_HORIZONTAL, WXC_FROM_DIP(5));

    m_StaticText22 = new wxStaticText(
        m_mainPanel, wxID_ANY, _("Valor 2"), wxDefaultPosition, wxDLG_UNIT(m_mainPanel, wxSize(-1, -1)), 0);

    boxSizer13->Add(m_StaticText22, 0, wxALL | wxALIGN_CENTER_HORIZONTAL, WXC_FROM_DIP(5));

    m_btnOk =
        new wxButton(m_mainPanel, wxID_ANY, _("Soma"), wxDefaultPosition, wxDLG_UNIT(m_mainPanel, wxSize(-1, -1)), 0);

    boxSizer13->Add(m_btnOk, 0, wxALL | wxALIGN_CENTER_HORIZONTAL, WXC_FROM_DIP(5));

    m_btnNOk = new wxButton(
        m_mainPanel, wxID_ANY, wxT("Subtração"), wxDefaultPosition, wxDLG_UNIT(m_mainPanel, wxSize(-1, -1)), 0);

    boxSizer13->Add(m_btnNOk, 0, wxALL | wxALIGN_CENTER_HORIZONTAL, WXC_FROM_DIP(5));

    wxBoxSizer* boxSizer15 = new wxBoxSizer(wxVERTICAL);

    boxSizer11->Add(boxSizer15, 1, wxALL | wxEXPAND, WXC_FROM_DIP(5));

    m_txtValor1 =
        new wxTextCtrl(m_mainPanel, wxID_ANY, wxT(""), wxDefaultPosition, wxDLG_UNIT(m_mainPanel, wxSize(-1, -1)), 0);
    m_txtValor1->SetFocus();
#if wxVERSION_NUMBER >= 3000
    m_txtValor1->SetHint(wxT(""));
#endif

    boxSizer15->Add(m_txtValor1, 0, wxRIGHT | wxTOP | wxBOTTOM, WXC_FROM_DIP(5));

    m_txtValor2 =
        new wxTextCtrl(m_mainPanel, wxID_ANY, wxT(""), wxDefaultPosition, wxDLG_UNIT(m_mainPanel, wxSize(-1, -1)), 0);
#if wxVERSION_NUMBER >= 3000
    m_txtValor2->SetHint(wxT(""));
#endif

    boxSizer15->Add(m_txtValor2, 0, wxRIGHT | wxTOP | wxBOTTOM, WXC_FROM_DIP(5));

    m_staticText31 = new wxStaticText(
        m_mainPanel, wxID_ANY, _("Resultado"), wxDefaultPosition, wxDLG_UNIT(m_mainPanel, wxSize(-1, -1)), 0);

    boxSizer15->Add(m_staticText31, 0, wxALL | wxALIGN_LEFT, WXC_FROM_DIP(5));

    m_txtResultado =
        new wxTextCtrl(m_mainPanel, wxID_ANY, wxT(""), wxDefaultPosition, wxDLG_UNIT(m_mainPanel, wxSize(-1, -1)), 0);
#if wxVERSION_NUMBER >= 3000
    m_txtResultado->SetHint(wxT(""));
#endif

    boxSizer15->Add(m_txtResultado, 0, wxRIGHT | wxTOP | wxBOTTOM, WXC_FROM_DIP(5));

    SetName(wxT("MainFrameBaseClass"));
    SetSize(wxDLG_UNIT(this, wxSize(500, 300)));
    if(GetSizer()) {
        GetSizer()->Fit(this);
    }
    if(GetParent()) {
        CentreOnParent(wxBOTH);
    } else {
        CentreOnScreen(wxBOTH);
    }
#if wxVERSION_NUMBER >= 2900
    if(!wxPersistenceManager::Get().Find(this)) {
        wxPersistenceManager::Get().RegisterAndRestore(this);
    } else {
        wxPersistenceManager::Get().Restore(this);
    }
#endif
    // Connect events
    m_btnOk->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::btnClickSoma), NULL, this);
    m_btnNOk->Connect(
        wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::btnClickSubtracao), NULL, this);
}

MainFrameBaseClass::~MainFrameBaseClass()
{
    m_btnOk->Disconnect(
        wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::btnClickSoma), NULL, this);
    m_btnNOk->Disconnect(
        wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::btnClickSubtracao), NULL, this);
}
