//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _PROJETO_WXFRAME_GUI_WXCRAFTER_BASE_CLASSES_H
#define _PROJETO_WXFRAME_GUI_WXCRAFTER_BASE_CLASSES_H

// clang-format off
#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/panel.h>
#include <wx/propgrid/manager.h>
#include <wx/propgrid/property.h>
#include <wx/propgrid/advprops.h>
#include <wx/button.h>
#include <wx/grid.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif

// clang-format on

class MainFrameBaseClass : public wxFrame
{
protected:
    wxPanel* m_mainPanel;
    wxPropertyGridManager* m_pgDados;
    wxPGProperty* m_pgNome;
    wxPGProperty* m_pgTipo;
    wxPGProperty* m_pgCorrente;
    wxPGProperty* m_pgTempo;
    wxPGProperty* m_pgITF;
    wxPGProperty* m_pgRTC;
    wxPGProperty* m_pgIAIF;
    wxPGProperty* m_pgTempoDefinido;
    wxPGProperty* m_pgTipoCurva;
    wxButton* m_button35;
    wxButton* m_button131;
    wxButton* m_button51;
    wxGrid* m_grid;

protected:
    virtual void onPGChange(wxPropertyGridEvent& event)
    {
        event.Skip();
    }
    virtual void btnClickAdicionar(wxCommandEvent& event)
    {
        event.Skip();
    }
    virtual void btnClickExcluir(wxCommandEvent& event)
    {
        event.Skip();
    }
    virtual void btnClickCoordenograma(wxCommandEvent& event)
    {
        event.Skip();
    }
    virtual void grid_CellSelected(wxGridEvent& event)
    {
        event.Skip();
    }

public:
    wxPropertyGridManager* GetPgDados()
    {
        return m_pgDados;
    }
    wxButton* GetButton35()
    {
        return m_button35;
    }
    wxButton* GetButton131()
    {
        return m_button131;
    }
    wxButton* GetButton51()
    {
        return m_button51;
    }
    wxGrid* GetGrid()
    {
        return m_grid;
    }
    wxPanel* GetMainPanel()
    {
        return m_mainPanel;
    }
    MainFrameBaseClass(wxWindow* parent,
        wxWindowID id = wxID_ANY,
        const wxString& title = _("Coordenograma"),
        const wxPoint& pos = wxDefaultPosition,
        const wxSize& size = wxSize(700, 400),
        long style = wxCAPTION | wxRESIZE_BORDER | wxMAXIMIZE_BOX | wxMINIMIZE_BOX | wxSYSTEM_MENU | wxCLOSE_BOX);
    virtual ~MainFrameBaseClass();
};

#endif
